build: Fix missing -lrt for clock_gettime()
librt is needed for using clock_gettime():

/usr/bin/ld: src/ntp.o: undefined reference to symbol 'clock_gettime@@GLIBC_2.2.5'
/usr/bin/ld: note: 'clock_gettime@@GLIBC_2.2.5' is defined in DSO /usr/lib/librt.so.1 so try adding it to the linker command line
/usr/lib/librt.so.1: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status